import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { OnboardingContainer } from "@/components/onboarding/OnboardingContainer";
import { OnboardingHeader } from "@/components/onboarding/OnboardingHeader";
import { ProgressDots } from "@/components/onboarding/ProgressDots";
import { NeomorphicInput } from "@/components/onboarding/NeomorphicInput";
import { NeomorphicButton } from "@/components/onboarding/NeomorphicButton";
import { useOnboardingStore } from "@/hooks/useOnboardingStore";
import { useDataContext } from "@/contexts/DataContext";
import { toast } from "sonner";

export default function CreateOrganisationScreen() {
  const navigate = useNavigate();
  const { orgName, setOrgName, setOrgId } = useOnboardingStore();
  const { refresh, session } = useDataContext();
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleCreate = async () => {
    if (!orgName.trim()) {
      setError("Organisation name is required");
      return;
    }

    setLoading(true);
    try {
      // Verify we have a valid session
      if (!session?.user) {
        toast.error("Please sign in to continue");
        navigate("/login");
        return;
      }

      const currentUserId = session.user.id;
      console.log("Creating org for user:", currentUserId);

      // Create organisation - slug is auto-generated by DB trigger
      // handle_new_organisation trigger will:
      // 1. Add user as org member
      // 2. Update user metadata with org_id
      const { data: org, error: orgError } = await supabase
        .from('organisations')
        .insert({
          name: orgName,
          created_by: currentUserId
        })
        .select()
        .single();

      if (orgError) {
        console.error("Org creation error:", orgError);
        throw orgError;
      }

      console.log("Org created:", org.id);

      // Store in local onboarding state
      setOrgId(org.id);

      // Refresh session to get fresh JWT with new org_id claim
      const { error: refreshError } = await supabase.auth.refreshSession();
      if (refreshError) {
        console.error("Session refresh error:", refreshError);
      }
      
      // Refresh DataContext to pick up the new org_id
      await refresh();
      
      toast.success("Organisation created!");
      navigate("/onboarding/add-property");
    } catch (err: any) {
      console.error("Create org failed:", err);
      toast.error(err.message || "Failed to create organisation");
    } finally {
      setLoading(false);
    }
  };

  return (
    <OnboardingContainer>
      <div className="animate-fade-in">
        <ProgressDots current={2} total={6} />
        
        <OnboardingHeader
          title="Create your organisation"
          subtitle="Give your team a home"
          showBack
          onBack={async () => {
            await supabase.auth.signOut();
            navigate("/login");
          }}
        />

        <div className="space-y-6">
          <NeomorphicInput
            label="Organisation Name"
            placeholder="Acme Property Group"
            value={orgName}
            onChange={(e) => {
              setOrgName(e.target.value);
              setError("");
            }}
            error={error}
          />

          <div className="pt-4">
            <NeomorphicButton
              variant="primary"
              onClick={handleCreate}
              disabled={loading || !orgName.trim()}
            >
              {loading ? "Creating..." : "Continue"}
            </NeomorphicButton>
          </div>
        </div>
      </div>
    </OnboardingContainer>
  );
}
