/**
 * Alternate space names → canonical space type name.
 * Used for icon lookup when user types a variation (e.g. "Sitting Room" → "Living Room").
 * Keys are lowercase for case-insensitive lookup.
 */
export const ALTERNATE_NAME_TO_CANONICAL: Record<string, string> = {
  // Residential
  "living room": "Living Room",
  "sitting room": "Living Room",
  "lounge": "Living Room",
  "bedroom": "Bedroom",
  "master bedroom": "Bedroom",
  "guest room": "Bedroom",
  "bathroom": "Bathroom",
  "family bathroom": "Bathroom",
  "wc": "WC",
  "toilet": "Toilet",
  "powder room": "WC",
  "shower room": "Shower Room",
  "kitchen": "Kitchen",
  "utility": "Utility",
  "garage": "Garage",
  "dining room": "Dining Room",
  "home office": "Home Office",
  "study": "Study",
  "playroom": "Playroom",
  "conservatory": "Conservatory",
  "sunroom": "Sunroom",
  "loft": "Loft",
  "attic": "Attic",
  "basement": "Basement",
  "cellar": "Cellar",
  "laundry room": "Laundry Room",
  "utility room": "Utility",
  "pantry": "Pantry",
  // Office
  "workspace": "Office",
  "open plan office": "Open Plan Office",
  "meeting room": "Meeting Room",
  "conference room": "Conference Room",
  "boardroom": "Boardroom",
  "reception": "Reception",
  "lobby": "Lobby",
  "breakout area": "Breakout Area",
  "canteen": "Canteen",
  "staff kitchen": "Staff Kitchen",
  "print room": "Print Room",
  "copy room": "Copy Room",
  "phone booth": "Phone Booth",
  "call room": "Call Room",
  "it room": "IT Room",
  "server room": "Server Room",
  "data room": "Data Room",
  "hr office": "HR Office",
  "training room": "Training Room",
  "classroom": "Classroom",
  "library": "Library",
  "archive room": "Archive Room",
  "stock room": "Stock Room",
  "retail floor": "Retail Floor",
  "sales floor": "Sales Floor",
  "workshop": "Workshop",
  "creative studio": "Creative Studio",
  "medical room": "Medical Room",
  "first aid": "First Aid",
  "laboratory": "Laboratory",
  "security room": "Security Room",
  // Sanitary
  "accessible wc": "Accessible WC",
  "disabled wc": "Disabled WC",
  "changing room": "Changing Room",
  "locker room": "Locker Room",
  "shower block": "Shower Block",
  // Technical
  "plant room": "Plant Room",
  "boiler room": "Boiler Room",
  "electrical room": "Electrical Room",
  "switch room": "Switch Room",
  "ups room": "UPS Room",
  "generator room": "Generator Room",
  "hvac room": "HVAC Room",
  "riser": "Riser",
  "service riser": "Service Riser",
  "lift": "Lift",
  "elevator": "Elevator",
  "lift motor room": "Lift Motor Room",
  "comms room": "Comms Room",
  // Circulation
  "corridor": "Corridor",
  "hallway": "Hallway",
  "staircase": "Staircase",
  "landing": "Landing",
  "entrance": "Entrance",
  "exit": "Exit",
  "fire escape": "Fire Escape",
  // External
  "garden": "Garden",
  "terrace": "Terrace",
  "balcony": "Balcony",
  "yard": "Yard",
  "courtyard": "Courtyard",
  "car park": "Car Park",
  "parking": "Parking",
  "bike store": "Bike Store",
  "loading bay": "Loading Bay",
  "bin store": "Bin Store",
  "roof": "Roof",
  "rooftop plant": "Rooftop Plant",
  // Storage
  "storage room": "Storage Room",
  "closet": "Closet",
  "cupboard": "Cupboard",
  "archive": "Archive",
  "break room": "Break Room",
};

/** Resolve user input to canonical space type name for icon lookup. */
export function resolveToCanonicalSpaceType(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return null;
  const lower = trimmed.toLowerCase();
  return ALTERNATE_NAME_TO_CANONICAL[lower] ?? trimmed;
}
