import { format } from 'date-fns';

interface AuditMetadataBlockProps {
  data?: {
    org?: string;
    date?: string;
    version?: string;
    generatedBy?: string;
  };
}

export default function AuditMetadataBlock({ data }: AuditMetadataBlockProps) {
  return (
    <div className="printable-section bg-white p-6 border-b border-gray-200">
      <div className="space-y-1 text-sm text-gray-700">
        <p>
          <span className="font-semibold">Organisation:</span>{' '}
          {data?.org ?? '—'}
        </p>
        <p>
          <span className="font-semibold">Date:</span>{' '}
          {data?.date ?? format(new Date(), 'PPP')}
        </p>
        {data?.version && (
          <p>
            <span className="font-semibold">Version:</span> {data.version}
          </p>
        )}
        <p>
          <span className="font-semibold">Generated By:</span>{' '}
          {data?.generatedBy ?? 'Filla Compliance System'}
        </p>
      </div>
    </div>
  );
}
