// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
// Types: npm run gen:types (local `supabase start`, not production --linked).

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Origin-scoped (app.filla.app). Never set cookie Domain=.filla.app — marketing
    // (www.filla.app) must not be able to read product sessions.
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

// Safe call wrapper for error handling
let errorHandler: ((msg: string | null) => void) | null = null;

export function registerErrorHandler(handler: (msg: string | null) => void) {
  errorHandler = handler;
}

export async function safeCall<T>(fn: () => Promise<T>): Promise<T> {
  try {
    const result: any = await fn();
    if (result?.error) {
      if (errorHandler) {
        const message = result.error.message || "Database operation failed";
        errorHandler(message);
      }
    }
    return result;
  } catch (err: any) {
    if (errorHandler) {
      const message = err.message || "Unexpected error occurred";
      errorHandler(message);
    }
    return { data: null, error: err } as T;
  }
}

// Debug only
if (import.meta.env.DEV) {
  (window as unknown as { supabase: typeof supabase }).supabase = supabase;
}
